#############################################################################
# Makefile for building: PITEST1
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  PITEST1.pro
# Template: app
# Command: /mnt/b/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/bin/qmake -o Makefile PITEST1.pro -spec /home/first/Qt/5.9/Src/qtbase/mkspecs/arm-linux-gnueabihf-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = arm-linux-gnueabihf-gcc
CXX           = arm-linux-gnueabihf-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe --sysroot=/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe --sysroot=/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5 -I/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtQuick -I/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui -I/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtQml -I/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtNetwork -I/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore -I. -I/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include -I/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/interface/vmcs_host/linux -I/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/interface/vcos/pthreads -I../Qt/5.9/Src/qtbase/mkspecs/arm-linux-gnueabihf-g++
QMAKE         = /mnt/b/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PITEST11.0.0
DISTDIR = /home/first/PITEST1/.tmp/PITEST11.0.0
LINK          = arm-linux-gnueabihf-g++
LFLAGS        = --sysroot=/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot
LIBS          = $(SUBLIBS) -L/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lrt -ldl -latomic -lGLESv2 -lbcm_host -lvcos -lvchiq_arm -lpthread 
AR            = arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_qml.cpp
OBJECTS       = main.o \
		qrc_qml.o
DIST          = ../Qt/5.9/Src/qtbase/mkspecs/features/spec_pre.prf \
		../Qt/5.9/Src/qtbase/mkspecs/common/unix.conf \
		../Qt/5.9/Src/qtbase/mkspecs/common/linux.conf \
		../Qt/5.9/Src/qtbase/mkspecs/common/sanitize.conf \
		../Qt/5.9/Src/qtbase/mkspecs/common/gcc-base.conf \
		../Qt/5.9/Src/qtbase/mkspecs/common/gcc-base-unix.conf \
		../Qt/5.9/Src/qtbase/mkspecs/common/g++-base.conf \
		../Qt/5.9/Src/qtbase/mkspecs/common/g++-unix.conf \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/qconfig.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dcore.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dcore_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dextras.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dextras_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dinput.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dinput_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dlogic.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquick.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquick_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquickextras.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquickinput.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquickrender.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3drender.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3drender_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_concurrent.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_concurrent_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_core.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_core_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_dbus.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_dbus_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_egl_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_fb_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_gui.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_gui_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_input_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_network.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_network_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_opengl.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_opengl_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_openglextensions.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_printsupport.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_printsupport_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_qml.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_qml_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_qmltest.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_qmltest_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quick.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quick_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quickwidgets.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_service_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_sql.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_sql_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_testlib.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_testlib_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_theme_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_webchannel.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_webchannel_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_websockets.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_websockets_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_widgets.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_widgets_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_xml.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_xml_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_zlib_private.pri \
		../Qt/5.9/Src/qtbase/mkspecs/features/qt_functions.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/qt_config.prf \
		../Qt/5.9/Src/qtbase/mkspecs/arm-linux-gnueabihf-g++/qmake.conf \
		../Qt/5.9/Src/qtbase/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.9/Src/qtbase/mkspecs/features/exclusive_builds.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/toolchain.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/default_pre.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/resolve_config.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/default_post.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/qml_debug.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/warn_on.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/qt.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/resources.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/moc.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/unix/opengl.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/unix/thread.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/qmake_use.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/file_copies.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/testcase_targets.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/exceptions.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/yacc.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/lex.prf \
		PITEST1.pro  main.cpp
QMAKE_TARGET  = PITEST1
DESTDIR       = 
TARGET        = PITEST1


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PITEST1.pro ../Qt/5.9/Src/qtbase/mkspecs/arm-linux-gnueabihf-g++/qmake.conf ../Qt/5.9/Src/qtbase/mkspecs/features/spec_pre.prf \
		../Qt/5.9/Src/qtbase/mkspecs/common/unix.conf \
		../Qt/5.9/Src/qtbase/mkspecs/common/linux.conf \
		../Qt/5.9/Src/qtbase/mkspecs/common/sanitize.conf \
		../Qt/5.9/Src/qtbase/mkspecs/common/gcc-base.conf \
		../Qt/5.9/Src/qtbase/mkspecs/common/gcc-base-unix.conf \
		../Qt/5.9/Src/qtbase/mkspecs/common/g++-base.conf \
		../Qt/5.9/Src/qtbase/mkspecs/common/g++-unix.conf \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/qconfig.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dcore.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dcore_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dextras.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dextras_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dinput.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dinput_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dlogic.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquick.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquick_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquickextras.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquickinput.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquickrender.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3drender.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3drender_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_concurrent.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_concurrent_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_core.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_core_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_dbus.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_dbus_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_egl_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_fb_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_gui.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_gui_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_input_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_network.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_network_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_opengl.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_opengl_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_openglextensions.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_printsupport.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_printsupport_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_qml.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_qml_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_qmltest.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_qmltest_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quick.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quick_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quickwidgets.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_service_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_sql.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_sql_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_testlib.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_testlib_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_theme_support_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_webchannel.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_webchannel_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_websockets.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_websockets_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_widgets.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_widgets_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_xml.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_xml_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_zlib_private.pri \
		../Qt/5.9/Src/qtbase/mkspecs/features/qt_functions.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/qt_config.prf \
		../Qt/5.9/Src/qtbase/mkspecs/arm-linux-gnueabihf-g++/qmake.conf \
		../Qt/5.9/Src/qtbase/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.9/Src/qtbase/mkspecs/features/exclusive_builds.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/toolchain.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/default_pre.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/resolve_config.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/default_post.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/qml_debug.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/warn_on.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/qt.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/resources.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/moc.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/unix/opengl.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/unix/thread.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/qmake_use.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/file_copies.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/testcase_targets.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/exceptions.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/yacc.prf \
		../Qt/5.9/Src/qtbase/mkspecs/features/lex.prf \
		PITEST1.pro \
		qml.qrc \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Quick.prl \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Gui.prl \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Qml.prl \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Network.prl \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Core.prl
	$(QMAKE) -o Makefile PITEST1.pro -spec /home/first/Qt/5.9/Src/qtbase/mkspecs/arm-linux-gnueabihf-g++ CONFIG+=debug CONFIG+=qml_debug
../Qt/5.9/Src/qtbase/mkspecs/features/spec_pre.prf:
../Qt/5.9/Src/qtbase/mkspecs/common/unix.conf:
../Qt/5.9/Src/qtbase/mkspecs/common/linux.conf:
../Qt/5.9/Src/qtbase/mkspecs/common/sanitize.conf:
../Qt/5.9/Src/qtbase/mkspecs/common/gcc-base.conf:
../Qt/5.9/Src/qtbase/mkspecs/common/gcc-base-unix.conf:
../Qt/5.9/Src/qtbase/mkspecs/common/g++-base.conf:
../Qt/5.9/Src/qtbase/mkspecs/common/g++-unix.conf:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/qconfig.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dcore.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dcore_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dextras.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dextras_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dinput.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dinput_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dlogic.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dlogic_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquick.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquick_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquickextras.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquickinput.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquickrender.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3drender.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_3drender_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_bootstrap_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_concurrent.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_concurrent_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_core.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_core_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_dbus.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_dbus_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_egl_support_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_fb_support_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_gui.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_gui_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_input_support_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_network.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_network_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_opengl.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_opengl_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_openglextensions.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_openglextensions_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_printsupport.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_printsupport_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_qml.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_qml_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_qmldebug_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_qmltest.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_qmltest_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quick.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quick_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quickcontrols2.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quickparticles_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quickwidgets.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_service_support_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_sql.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_sql_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_testlib.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_testlib_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_theme_support_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_webchannel.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_webchannel_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_websockets.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_websockets_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_widgets.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_widgets_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_xml.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_xml_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_xmlpatterns.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/modules/qt_lib_zlib_private.pri:
../Qt/5.9/Src/qtbase/mkspecs/features/qt_functions.prf:
../Qt/5.9/Src/qtbase/mkspecs/features/qt_config.prf:
../Qt/5.9/Src/qtbase/mkspecs/arm-linux-gnueabihf-g++/qmake.conf:
../Qt/5.9/Src/qtbase/mkspecs/features/spec_post.prf:
.qmake.stash:
../Qt/5.9/Src/qtbase/mkspecs/features/exclusive_builds.prf:
../Qt/5.9/Src/qtbase/mkspecs/features/toolchain.prf:
../Qt/5.9/Src/qtbase/mkspecs/features/default_pre.prf:
../Qt/5.9/Src/qtbase/mkspecs/features/resolve_config.prf:
../Qt/5.9/Src/qtbase/mkspecs/features/default_post.prf:
../Qt/5.9/Src/qtbase/mkspecs/features/qml_debug.prf:
../Qt/5.9/Src/qtbase/mkspecs/features/warn_on.prf:
../Qt/5.9/Src/qtbase/mkspecs/features/qt.prf:
../Qt/5.9/Src/qtbase/mkspecs/features/resources.prf:
../Qt/5.9/Src/qtbase/mkspecs/features/moc.prf:
../Qt/5.9/Src/qtbase/mkspecs/features/unix/opengl.prf:
../Qt/5.9/Src/qtbase/mkspecs/features/unix/thread.prf:
../Qt/5.9/Src/qtbase/mkspecs/features/qmake_use.prf:
../Qt/5.9/Src/qtbase/mkspecs/features/file_copies.prf:
../Qt/5.9/Src/qtbase/mkspecs/features/testcase_targets.prf:
../Qt/5.9/Src/qtbase/mkspecs/features/exceptions.prf:
../Qt/5.9/Src/qtbase/mkspecs/features/yacc.prf:
../Qt/5.9/Src/qtbase/mkspecs/features/lex.prf:
PITEST1.pro:
qml.qrc:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Quick.prl:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Gui.prl:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Qml.prl:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Network.prl:
/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile PITEST1.pro -spec /home/first/Qt/5.9/Src/qtbase/mkspecs/arm-linux-gnueabihf-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/bin/rcc \
		Page1Form.ui.qml \
		Page1.qml \
		qtquickcontrols2.conf \
		main.qml
	/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/features/data/dummy.cpp
	arm-linux-gnueabihf-g++ -pipe --sysroot=/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp /media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui/QGuiApplication \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui/qguiapplication.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui/qtguiglobal.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qglobal.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qconfig-bootstrapped.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qconfig.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qtcore-config.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qsystemdetection.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qprocessordetection.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qcompilerdetection.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qtypeinfo.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qsysinfo.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qlogging.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qflags.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qtypetraits.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qatomic.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qbasicatomic.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qgenericatomic.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qatomic_msvc.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qglobalstatic.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qmutex.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qnumeric.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qversiontagging.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui/qtgui-config.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qcoreapplication.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qstring.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qchar.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qbytearray.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qrefcount.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qnamespace.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qarraydata.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/string.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/features.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/stdc-predef.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/sys/cdefs.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/wordsize.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/gnu/stubs.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/gnu/stubs-hard.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/xlocale.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/string.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/string2.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/endian.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/endian.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/byteswap.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/types.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/typesizes.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/byteswap-16.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/stdlib.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/waitflags.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/waitstatus.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/sys/types.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/time.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/time.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/timex.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/sys/select.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/select.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/sigset.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/select2.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/sys/sysmacros.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/pthreadtypes.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/alloca.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/stdlib-bsearch.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/stdlib-float.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/stdlib.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/stdlib-ldbl.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/string3.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qstringbuilder.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qobject.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qobjectdefs.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qlist.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qalgorithms.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qiterator.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qhashfunctions.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qpair.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/limits.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/posix1_lim.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/local_lim.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/linux/limits.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/posix2_lim.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/xopen_lim.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/stdio_lim.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qbytearraylist.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qstringlist.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qregexp.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qstringmatcher.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qcoreevent.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qscopedpointer.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qmetatype.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qvarlengtharray.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qcontainerfwd.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qobject_impl.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qeventloop.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui/qwindowdefs.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui/qinputmethod.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qlocale.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qvariant.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qmap.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qdebug.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qhash.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qtextstream.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qiodevice.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/stdio.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/libio.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/_G_config.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/wchar.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/wchar.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/wctype.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/wchar2.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/wchar-ldbl.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/gconv.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/libio-ldbl.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/sys_errlist.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/getopt.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/ctype.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/stdio.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/stdio2.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/bits/stdio-ldbl.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qvector.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qpoint.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qset.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qcontiguouscache.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qsharedpointer.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qshareddata.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qsize.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtQml/QQmlApplicationEngine \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtQml/qqmlapplicationengine.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtQml/qqmlengine.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qurl.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qurlquery.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtQml/qjsengine.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtQml/qjsvalue.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtQml/qtqmlglobal.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtQml/qtqml-config.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtNetwork/qtnetworkglobal.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtNetwork/qtnetwork-config.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtQml/qqml.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtQml/qqmlprivate.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtQml/qqmlparserstatus.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtQml/qqmlpropertyvaluesource.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtQml/qqmllist.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore/qmetaobject.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtQml/qqmlerror.h \
		/media/first/e6931503-f01e-4d6f-8864-4f510792c6ca/buildroot/raspi_qt5/buildroot-2017.05.1/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtQml/qqmldebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/PITEST1/bin || mkdir -p $(INSTALL_ROOT)/opt/PITEST1/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/PITEST1/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/PITEST1/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/PITEST1/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

